### PR TITLE
Create docker image publish workflow

### LINKED ISSUE #32: Pipeline should build & push docker image on main after other steps succeed

### PR DESCRIPTION
**Pull request by leolazz**
line 3 changed to run only for pull request.

line 10 a if statement added to check merged event.

Honestly, I am not sure if this will work. The information on doing this wasn't very clear to me.

closes #32

### CODE REVIEW

**Comment by gianlazz** [comment]
This looks great but let's get this flow to depend on the other steps that happen in main (build, test, etc.)

**Comment by leolazz** [comment]
It seems to work, since it hasn't run without this being merged.

**Comment by leolazz** [comment]
I think this is the best functionality I can get for now. 

There may be a better way to do this with a 3rd party tool though. There just isn't a way I can find to link the usage of one test to the result of another, besides possibly using artifacts that could be generated from a unit test.

For now, all the tests will run expect the build and publish image unless merged to main. But since it is the last event it should only run if prior pass.

**Review by gianlazz — APPROVED** [review]
Looks good 👍

**Pull request merged**
